# Generated by Django 4.0.2 on 2022-03-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0007_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
